### ISSUE TITLE
Screenshots are missing

### ISSUE THREAD

**Issue by aastudio** [bigethan/hologram-addons#2]

**Comment by bigethan** [comment]
Thanks!  Will get them sorted in a couple weeks after I get back from http://www.paganello.com

**Comment by gil--** [comment]
Any chance for screenshots? Also wondering if this still works as I can't seem to get anything to show locally.


edit:

Looks like maybe the API has changed. 

Line 91:
`var mainCssRules = document.styleSheets[0].rules;`
to
`var mainCssRules = document.styleSheets[5].cssRules;`

styleSheets[0] only works if your stylesheet is the main styling on the page. In my case, it was [5].

**Comment by bigethan** [comment]
yeah, this is a super deprecated project.  I'll take a look at it this week. wouldn't be surprised if hologram has evolved a bit. Or if you want to fork it and take over, I can point this repo to yours...

**Comment by bigethan** [comment]
ok, screenshots fixed and `cssRules` in place. in less than a year!  :upside_down_face:
